server:
  port: 8088

spring:
  datasource:
    url: jdbc:mysql://121.40.144.144:3306/xiaoxuewang?useUnicode=true&characterEncoding=utf-8&useAffectedRows=true
    username: root
    password: xiao!@WANG01

  thymeleaf:
      prefix: classpath:/static/

## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  #type-aliases-package: com.xiao.*.dto  # 注意：对应实体类的路径

logging:
  config: classpath:logback.xml
  path: ./logs
  #level: info 添加会报错
